---
driver_plugin: vagrant


platforms:
- name: centos-6.6
  run_list:
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]


suites:
- name: source
  run_list:
  - recipe[erlang::esl]
  - recipe[couch-test::source]
- name: lwrps
  run_list:
  - recipe[erlang::esl]
  - recipe[couch-test::lwrps]
- name: package
  excludes:
  - centos-6.6
  - centos-7.0
  run_list:
  - recipe[couch-test::package]
